### ISSUE TITLE
jsAuthGoogle não recupera email

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [JonatanSouza04/Firemonkey-jsAuth#1]
o componente não recupera o email do google

**Comment by JonatanSouza04** [comment]
Verifique o campo Scope e define as permissões que deseja.

Procure por Scope no Google.

Em 14 de fev de 2017 1:35 PM, "bugfreedobrasil" <notifications@github.com>
escreveu:

**Comment by Alexandre-Bernardes** [comment]
Esse scopo não é padrao do componente???
Inclusive no exemplo nao recupera email!
mas vou verificar. obg

**Comment by JonatanSouza04** [comment]
Se a propriedade estiver em branco eu pego um padrão, mas vc pode definir
outras permissões.


Em 14 de fev de 2017 1:40 PM, "Alexandre Bernardes" <
notifications@github.com> escreveu:

**Comment by Alexandre-Bernardes** [comment]
olhando o fonte, o padrao definido é plus.login somente e mais nada.
Há sim um padrao definido mas é no outro componente (jsAuthFacebook).
Ja existe o comando no componente (lrequest.response.getsimplevalue) para obter o email do json, mas aparentemente o json não tras o email.
to estudando aqui pra tentar resolver.

**Comment by JonatanSouza04** [comment]
Utilize o Scope Https://www.googleapis.com/auth/userinfo.email que você consegue recuperar o email.
Hoje eu atualizei o componente para Auth Google.
